export const projects = [
  {
    id: 1,
    name: 'Haircut',
    git_repo: 'https://github.com/POMAC-EGYPT/HaircutterWebsite',
    date: '07/2023 - 07/2023',
    techs: ['Angular', 'SASS', 'Angular Material', 'Rxjs'],
    description:
      'Haircut is a comprehensive booking platform for hair salons, featuring service selection, real-time appointment scheduling, and secure payment integration.',
    role: 'Maintained and refactored core application features for better scalability, optimizing rendering performance by reducing unnecessary re-renders.',
    company: 'POMAC',
    live_site: 'https://haircut.pomac.info',
  },
  {
    id: 2,
    name: 'Ward - Dashboard',
    git_repo: 'https://github.com/POMAC-EGYPT/wardAdmin',
    date: '05/2023 - 07/2023',
    techs: ['Angular', 'SASS', 'Bootstrap'],
    description: 'Ward is a comprehensive selling platform for flowers.',
    role: "Developed and maintained the admin dashboard for Ward, enabling efficient management of flower products, orders, and customer data. Implemented key features such as product categorization, inventory tracking, and order processing, significantly improving the platform's administrative capabilities.",
    company: 'POMAC',
    live_site: '-',
  },
  {
    id: 3,
    name: 'Bazzar - Dashboard',
    git_repo: 'https://github.com/ahmedSam22/bazar-admin',
    date: '02/2023 - 05/2023',
    techs: ['Angular', 'SASS', 'Bootstrap'],
    description: 'Bazzar is a comprehensive e-commerce platform.',
    role: "Developed and maintained the admin dashboard for Bazzar, enabling efficient management of products, orders, and customer data. Implemented key features such as product categorization, inventory tracking, and order processing, significantly improving the platform's administrative capabilities.",
    company: 'POMAC',
    live_site: '-',
  },
  {
    id: 4,
    name: 'IPE - Dashboard',
    git_repo: 'https://github.com/ahmedSam22/sha7n-admin',
    date: '10/2022 - 02/2023',
    techs: ['Angular', 'SASS', 'Bootstrap'],
    description: 'IPE is a comprehensive transportation platform.',
    role: "Developed and maintained the admin dashboard for IPE, enabling efficient management of transportation services, orders, and customer data. inventory tracking, and order processing, significantly improving the platform's administrative capabilities.",
    company: 'POMAC',
    live_site: '-',
  },
  {
    id: 5,
    name: 'IPE',
    git_repo: 'https://github.com/ahmedSam22/new-sha7n',
    date: '08/2022 - 10/2022',
    techs: ['Angular', 'SASS', 'Angular Material'],
    description: 'IPE is a comprehensive transportation platform.',
    role: 'Developed and maintained the user side for IPE, which involves managing shipments, tracking packages, and handling payments.',
    company: 'POMAC',
    live_site: 'https://ipe2w.com/home',
  },
  {
    id: 6,
    name: 'Teacher Package - Dashboard',
    git_repo: 'https://github.com/POMAC-EGYPT/HuzmhAdmin',
    date: '07/2022 - 08/2022',
    techs: ['Angular', 'SASS', 'Bootstrap'],
    description: 'Interactive Platform between students and teachers',
    role: 'developed admin dashboard for teacher package to manage students and packages',
    company: 'POMAC',
    live_site: '-',
  },
  {
    id: 7,
    name: 'Teacher Package',
    git_repo: 'https://github.com/ahmedSam22/new-sha7n',
    date: '05/2022 - 11/2022',
    techs: ['Angular', 'SASS', 'Angular Material', 'Firebase'],
    description: 'Teacher Package is a comprehensive platform for teachers.',
    role: 'developed user side for teacher package Interact with teachers and students',
    company: 'POMAC',
    live_site: 'https://huzmh.sa/',
  },
  {
    id: 8,
    name: 'LDM',
    git_repo: '-',
    date: '12/2023 - 12/2025',
    techs: ['Angular', 'Angular Material', 'KendoUi'],
    description: 'LDM is a comprehensive laboratory management system.',
    role: ' Maintained and refactored core application features for better scalability, optimizing rendering performance by reducing unnecessary re-renders.',
    company: 'National Technology',
    live_site: 'https://ldm.alborglaboratories.com',
  },
  {
    id: 9,
    name: 'Unified Animal Health System',
    git_repo: '-',
    date: '12/2024 - 12/2025',
    techs: ['Angular', 'Angular Material', 'KendoUi'],
    description:
      'Unified Animal Health System is a comprehensive system for animal health management.',
    role: 'Built the project from scratch as part of a small core team, developing a Pet Health Platform.',
    company: 'National Technology',
    live_site: '-',
  },
  {
    id: 10,
    name: 'Home Visits',
    git_repo: '-',
    date: '12/2024 - 12/2025',
    techs: ['Angular', 'Angular Material', 'KendoUi'],
    description: 'Home Sampling Booking feature, allowing patients to schedule home visits for medical collection and lab deliver (LDM Expand).',
    role: 'Architected and implemented the frontend from the ground up as a key contributor in a small core team.',
    company: 'National Technology',
    live_site: '-',
  },
];
